service: starkbank-webhook
provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  memorySize: 128 
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: main.app
    packRequirements: false
functions:
  webhook:
    handler: wsgi_handler.handler
    events: 
      - http: POST /
      - http: 'POST {proxy+}'
  generate_random_data:
    handler: app.lambda_scheduler.lambda_handler
    events:
      - schedule:
          rate: rate(3 hours)
          enabled: true
useDotenv: true
