service: starkbank-webhook
provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  memorySize: 128 
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: app.app.app
    packRequirements: false
functions:
  webhook:
    handler: wsgi_handler.handler
    events: 
      - http: POST
      - http: 'POST {proxy+}'
    layers: 
      - {Ref: PythonRequirementsLambdaLayer}
